import type { Metadata } from "next";
import { Pangolin } from "next/font/google";
import "./globals.css";

const pangolin = Pangolin({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-pangolin',
});

export const metadata: Metadata = {
  title: "Valentines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pangolin.variable}`}>
        {children}
      </body>
    </html>
  );
}
